import { FilmPreset, FilmPresetId, PresetCategory } from '../types';

export const FILM_CATEGORIES: { id: PresetCategory; label: string; count: number }[] = [
  { id: '35mm', label: '35mm Film', count: 4 },
  { id: 'digital_instant', label: 'Digital & Instant', count: 3 },
  { id: 'artistic', label: 'Artistic & Format', count: 3 },
];

export const FILM_PRESETS: Record<FilmPresetId, FilmPreset> = {
  // === KATEGORI 35MM FILM ===
  classic_90: {
    id: 'classic_90',
    name: "Classic '90",
    badge: 'GOLD 400',
    category: '35mm',
    categoryLabel: '35mm Film',
    cameraModel: 'Kodak FunSaver',
    iso: 400,
    cssFilter: 'sepia(18%) contrast(114%) saturate(130%) brightness(96%)',
    description: 'Warm golden tone dengan kontras alami, lifted analog blacks, soft red-orange halation glow, dan random orange light leak khas kamera sekali pakai.',
    icon: 'camera_roll',
    defaultGrain: 65,
    defaultLightLeak: 55,
    yearVibe: "'96",
    colorHex: '#ff5708',
    halationIntensity: 65,
    chromaticAberration: 3.5,
    toneCurve: {
      blackLift: 18,
      shadowTint: { r: 14, g: 8, b: 2 },
      midtoneWarmth: 16,
      highlightRollOff: 14,
      contrast: 1.15,
      saturation: 1.25,
      sepia: 15,
    },
  },
  premium_35mm: {
    id: 'premium_35mm',
    name: 'Premium 35mm',
    badge: 'T4 ZEISS',
    category: '35mm',
    categoryLabel: '35mm Film',
    cameraModel: 'Yashica T4 / Carl Zeiss',
    iso: 200,
    cssFilter: 'contrast(116%) saturate(122%) brightness(101%) sepia(8%)',
    description: 'Rich warm tone dengan ketajaman optik tinggi lensa Carl Zeiss T*, vignette halus, micro-contrast seimbang, dan highlight bloom lembut.',
    icon: 'lens',
    defaultGrain: 30,
    defaultLightLeak: 20,
    yearVibe: "'94",
    colorHex: '#e07a5f',
    halationIntensity: 45,
    chromaticAberration: 1.2,
    toneCurve: {
      blackLift: 10,
      shadowTint: { r: 8, g: 4, b: 0 },
      midtoneWarmth: 12,
      highlightRollOff: 12,
      contrast: 1.18,
      saturation: 1.22,
      sepia: 8,
    },
  },
  rangefinder_70s: {
    id: 'rangefinder_70s',
    name: '70s Warm',
    badge: 'TRIP 35',
    category: '35mm',
    categoryLabel: '35mm Film',
    cameraModel: 'Olympus Trip 35',
    iso: 200,
    cssFilter: 'sepia(28%) hue-rotate(-8deg) contrast(106%) saturate(115%) brightness(103%)',
    description: 'Tonal keemasan dan kecokelatan bernuansa 1970-an dengan faded green/yellow tint, lifted blacks, dan kontras lembut khas lensa selenium rangefinder.',
    icon: 'history_edu',
    defaultGrain: 50,
    defaultLightLeak: 40,
    yearVibe: "'76",
    colorHex: '#d4a373',
    halationIntensity: 30,
    chromaticAberration: 2.0,
    toneCurve: {
      blackLift: 28,
      shadowTint: { r: 18, g: 16, b: 0 },
      midtoneWarmth: 26,
      highlightRollOff: 18,
      contrast: 1.05,
      saturation: 1.15,
      sepia: 25,
    },
  },
  half_frame: {
    id: 'half_frame',
    name: 'Half Frame',
    badge: 'PEN F',
    category: '35mm',
    categoryLabel: '35mm Film',
    cameraModel: 'Olympus Pen F',
    iso: 400,
    cssFilter: 'contrast(112%) saturate(118%) sepia(12%) brightness(98%)',
    description: 'Format legendaris 72-eksposur dengan 2 frame vertikal berdampingan (diptych) dalam satu klise 35mm horizontal dipisahkan garis pembagi film.',
    icon: 'view_column',
    defaultGrain: 60,
    defaultLightLeak: 35,
    yearVibe: "'69",
    colorHex: '#e76f51',
    halationIntensity: 40,
    chromaticAberration: 2.5,
    isHalfFrame: true,
    toneCurve: {
      blackLift: 16,
      shadowTint: { r: 10, g: 6, b: 2 },
      midtoneWarmth: 12,
      highlightRollOff: 14,
      contrast: 1.12,
      saturation: 1.18,
      sepia: 12,
    },
  },

  // === KATEGORI DIGITAL & INSTANT ===
  y2k_ccd: {
    id: 'y2k_ccd',
    name: 'Y2K Digicam',
    badge: 'IXY CCD',
    category: 'digital_instant',
    categoryLabel: 'Digital & Instant',
    cameraModel: 'Canon IXY / CCD Sensor',
    iso: 800,
    cssFilter: 'contrast(128%) hue-rotate(12deg) saturate(155%) brightness(102%)',
    description: 'Cool blueish tone, kontras midtone tajam, sensor noise digital awal 2000-an, serta pembiasan kromatik khas sensor CCD saku.',
    icon: 'camera',
    defaultGrain: 38,
    defaultLightLeak: 25,
    yearVibe: "'02",
    colorHex: '#38bdf8',
    halationIntensity: 35,
    chromaticAberration: 5.0,
    toneCurve: {
      blackLift: 10,
      shadowTint: { r: -6, g: 6, b: 20 },
      midtoneWarmth: -14,
      highlightRollOff: 8,
      contrast: 1.28,
      saturation: 1.45,
      sepia: 0,
    },
  },
  faded_polaroid: {
    id: 'faded_polaroid',
    name: 'Instant Pola 600',
    badge: 'POLA 600',
    category: 'digital_instant',
    categoryLabel: 'Digital & Instant',
    cameraModel: 'Polaroid Sun 660',
    iso: 640,
    cssFilter: 'brightness(108%) contrast(92%) sepia(35%) saturate(115%)',
    description: 'Faded milky blacks (lifted shadows), sepia-cream tint lembut, highlight halation hangat, dan tekstur khas kertas foto instan 600.',
    icon: 'photo_size_select_actual',
    defaultGrain: 55,
    defaultLightLeak: 68,
    yearVibe: "'89",
    colorHex: '#f59e0b',
    halationIntensity: 80,
    chromaticAberration: 4.2,
    toneCurve: {
      blackLift: 34,
      shadowTint: { r: 26, g: 16, b: 4 },
      midtoneWarmth: 24,
      highlightRollOff: 20,
      contrast: 0.94,
      saturation: 1.12,
      sepia: 32,
    },
  },
  vhs_1998: {
    id: 'vhs_1998',
    name: 'VHS Camcorder 1998',
    badge: 'HANDYCAM',
    category: 'digital_instant',
    categoryLabel: 'Digital & Instant',
    cameraModel: 'Sony Handycam Hi8',
    iso: 320,
    cssFilter: 'contrast(120%) saturate(135%) brightness(102%) hue-rotate(-5deg)',
    description: 'Scanlines horizontal CRT, interlaced magnetic tape noise, chromatic aberration pita analog, dan timestamp OSD hijau/putih "REC 🟢 PLAY".',
    icon: 'videocam',
    defaultGrain: 70,
    defaultLightLeak: 15,
    yearVibe: "'98",
    colorHex: '#10b981',
    halationIntensity: 50,
    chromaticAberration: 6.0,
    isVhs: true,
    toneCurve: {
      blackLift: 22,
      shadowTint: { r: -4, g: 12, b: -2 },
      midtoneWarmth: -4,
      highlightRollOff: 10,
      contrast: 1.2,
      saturation: 1.35,
      sepia: 0,
    },
  },

  // === KATEGORI ARTISTIC & FORMAT ===
  bw_noir: {
    id: 'bw_noir',
    name: 'B&W Street Noir',
    badge: 'TRI-X 1600',
    category: 'artistic',
    categoryLabel: 'Artistic & Format',
    cameraModel: 'Leica M6 + Tri-X 400',
    iso: 1600,
    cssFilter: 'grayscale(100%) contrast(142%) brightness(90%)',
    description: 'Monokrom kontras tinggi push-processed dengan silver-halide grain perak tebal, shadow dramatis pekat dengan lifted floor, dan highlight glow.',
    icon: 'monochrome_photos',
    defaultGrain: 85,
    defaultLightLeak: 15,
    yearVibe: "'92",
    colorHex: '#d4d4d8',
    halationIntensity: 75,
    chromaticAberration: 0,
    toneCurve: {
      blackLift: 16,
      shadowTint: { r: 0, g: 0, b: 0 },
      midtoneWarmth: 0,
      highlightRollOff: 18,
      contrast: 1.42,
      saturation: 0.0,
      sepia: 0,
    },
  },
  medium_format: {
    id: 'medium_format',
    name: 'Medium Format 1:1',
    badge: 'HASSELBLAD',
    category: 'artistic',
    categoryLabel: 'Artistic & Format',
    cameraModel: 'Hasselblad 503CW',
    iso: 100,
    cssFilter: 'contrast(115%) saturate(138%) brightness(98%)',
    description: 'Aspect ratio 1:1 format 6x6 legendaris dengan saturasi warna mendalam, rendering tiga dimensi lembut, detail tajam, dan grain ultra-halus.',
    icon: 'crop_square',
    defaultGrain: 20,
    defaultLightLeak: 20,
    yearVibe: "'84",
    colorHex: '#06b6d4',
    halationIntensity: 35,
    chromaticAberration: 0.8,
    isMediumFormat: true,
    toneCurve: {
      blackLift: 10,
      shadowTint: { r: 4, g: 2, b: 8 },
      midtoneWarmth: 6,
      highlightRollOff: 16,
      contrast: 1.2,
      saturation: 1.4,
      sepia: 4,
    },
  },
  toy_camera: {
    id: 'toy_camera',
    name: 'Toy Camera',
    badge: 'HOLGA 120',
    category: 'artistic',
    categoryLabel: 'Artistic & Format',
    cameraModel: 'Holga 120N',
    iso: 400,
    cssFilter: 'contrast(125%) saturate(145%) sepia(20%) brightness(95%)',
    description: 'Heavy tunnel vignette melengkung, ketidaksempurnaan lensa plastik, chromatic aberration kuat, lifted murky blacks, dan light leak acak tebal.',
    icon: 'toys',
    defaultGrain: 80,
    defaultLightLeak: 85,
    yearVibe: "'82",
    colorHex: '#ec4899',
    halationIntensity: 70,
    chromaticAberration: 7.5,
    toneCurve: {
      blackLift: 32,
      shadowTint: { r: 20, g: 10, b: 0 },
      midtoneWarmth: 18,
      highlightRollOff: 22,
      contrast: 1.25,
      saturation: 1.42,
      sepia: 20,
    },
  },
};

export const FILM_PRESET_LIST = Object.values(FILM_PRESETS);

export const PRESETS_BY_CATEGORY: Record<PresetCategory, FilmPreset[]> = {
  '35mm': FILM_PRESET_LIST.filter((p) => p.category === '35mm'),
  'digital_instant': FILM_PRESET_LIST.filter((p) => p.category === 'digital_instant'),
  'artistic': FILM_PRESET_LIST.filter((p) => p.category === 'artistic'),
};
